name: Flyway Migrate

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "migrations/**"

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: af-south-1

      - name: Get outputs
        uses: dflook/terraform-output@v1
        id: tf-outputs
        with:
          path: terraform

      - name: Install PostgreSQL Client
        run: sudo apt-get install -y postgresql-client

      - name: Create Database
        run: chmod +x ./create_db.sh && ./create_db.sh

      - name: Flyway validate and migrate
        uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:postgresql://${{ steps.tf-outputs.outputs.kudos_db_endpoint }}/kudos
          user: ${{ steps.tf-outputs.outputs.kudos_db_user }}
          password: ${{ steps.tf-outputs.outputs.kudos_db_password }}
          locations: filesystem:./migrations
        env:
          FLYWAY_VALIDATE_MIGRATION_NAMING: true
